version: '3.7'
services:
  api:
    build: .
    image: "hongikapi"
    ports:
      - "4000:4000"
      - "6500:6500"
    restart: "unless-stopped"
    depends_on:
      - db
      - redis
      - mongo
    networks:
      - api-network
  db:
    image: mysql
    ports:
      - "3600:3306"
    restart: "unless-stopped"
    environment:
      - MYSQL_ROOT_PASSWORD=password1234!
      - MYSQL_ROOT_HOST=%
    networks:
      - api-network
    volumes:
      - hongik-api-volume-production:/var/lib/mysql
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: "unless-stopped"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password1234!
      - MONGO_INITDB_DATABASE=hongik
    networks:
      - api-network
    volumes:
      - hongik-api-mongo-production:/data/db
  redis:
    image: arm64v8/redis
    restart: "unless-stopped"
    ports:
      - "6379:6379"
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
volumes:
  hongik-api-volume-production:
  hongik-api-mongo-production:
