version: '3.7'
services:
  api:
    build: .
    image: "hongikapi-dev-container"
    ports:
      - "4000:4000"
      - "5500:6000"
    restart: "unless-stopped"
    volumes:
      - ..:/api
    depends_on:
      - db
      - redis
    networks:
      - api-network
    tty: true
  db:
    image: mysql
    ports:
      - "3600:3306"
    restart: "unless-stopped"
    environment:
      - MYSQL_ROOT_PASSWORD=password1234!
      - MYSQL_ROOT_HOST=%
    networks:
      - api-network
    volumes:
      - hongik-api-volume:/var/lib/mysql
  redis:
    image: arm64v8/redis
    restart: "unless-stopped"
    ports:
      - "6379:6379"
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
volumes:
  hongik-api-volume:
